@startuml
left to right direction

actor "Неавторизованный\nпользователь" as UserNotAuf
actor "Пользователь\nприложения" as User
actor "Администратор\nсистемы" as Admin

' Наследование: авторизованный пользователь = частный случай неавторизованного
UserNotAuf <|-- User

usecase "Сканировать\nупаковку" as UC_Scan
usecase "Получить\nподсветку даты" as UC_Highlight

usecase "Авторизоваться" as UC_AuthUser
usecase "Зарегистрироваться" as UC_Register

usecase "Сообщить\nоб ошибке" as UC_Report
usecase "Положить продукт\nна хранение" as UC_Keep
usecase "Просмотреть продукты\nна хранении" as UC_KeepView
usecase "Удалить продукт\nс хранения" as UC_KeepDel
usecase "Получить дату\nизготовления" as UC_GetExprDate
usecase "Отсканировать дату\nизготовления" as UC_ScanExprDate
usecase "Ввести дату\nизготовления вручную" as UC_EnterExprDate

' Админские кейсы
usecase "Запустить\nдообучение модели" as UC_Retrain
usecase "Проанализировать\nстатистику качества" as UC_Stats
usecase "Просмотреть список\nпользователей" as UC_Users
usecase "Заблокировать\nпользователя" as UC_UserBlock
usecase "Просмотреть сообщения\nоб ошибках" as UC_Messages
usecase "Удалить сообщения\nоб ошибках" as UC_MessageDel

' Ассоциации с кратностями (актер — 1, запусков use case — 0..*)
UserNotAuf "1" -- "*" UC_Register
UserNotAuf "1" -- "1" UC_AuthUser
UserNotAuf "1" -- "*" UC_Scan

User "1" -- "*" UC_Report
User "1" -- "*" UC_Keep
User "1" -- "*" UC_KeepView

Admin "1" -- "*" UC_Retrain
Admin "1" -- "*" UC_Stats
Admin "1" -- "*" UC_Users
Admin "1" -- "*" UC_Messages

' Подсветка даты всегда часть сценария сканирования
UC_Scan ..> UC_Highlight : <<include>>

' Пары "просмотр / удаление" и "просмотр / действие" – расширения

' Сначала просмотр сообщений, уже из него можно удалять
UC_MessageDel ..> UC_Messages : <<extend>>

' Сначала список пользователей, потом из него можно блокировать
UC_UserBlock ..> UC_Users : <<extend>>

' Сначала просмотр товаров на хранении, потом можно удалять
UC_KeepDel ..> UC_KeepView : <<extend>>

' Положить на хранение обязательно включает получение даты
UC_Keep ..> UC_GetExprDate : <<include>>

' Получить дату можно двумя альтернативными сценариями
UC_GetExprDate <|-- UC_ScanExprDate
UC_GetExprDate <|-- UC_EnterExprDate
' что бы отсканировать дату вначале нужно что бы её подсветило
UC_ScanExprDate ..> UC_Highlight : <<include>>

@enduml
